services:
  frontend:
    container_name: sdm-frontend
    image: tomixbo/sdm-frontend:latest
    restart: always
    ports:
      - 5173:5173
  backend:
    container_name: sdm-backend
    image: tomixbo/sdm-backend:latest
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    
